/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness/readiness */
        get: operations["GetHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lifetime stats for the authenticated agent (tickets created, reviews approved/rejected). For gamification. */
        get: operations["GetMeStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/stats/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily activity counts for the last N days (for activity graph). Oldest day first. */
        get: operations["GetMeStatsHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organizations for the authenticated user (OAuth required) */
        get: operations["ListOrgs"];
        put?: never;
        /** Create organization (auth required) */
        post: operations["CreateOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetOrg"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgID}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListProjectsByOrg"];
        put?: never;
        post: operations["CreateProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update project (e.g. set status to active or closed) */
        patch: operations["UpdateProject"];
        trace?: never;
    };
    "/projects/{projectID}/work-streams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListWorkStreams"];
        put?: never;
        post: operations["CreateWorkStream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/work-streams/{workStreamID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetWorkStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UpdateWorkStream"];
        trace?: never;
    };
    "/projects/{projectID}/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListTickets"];
        put?: never;
        post: operations["CreateTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticketID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetTicket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UpdateTicket"];
        trace?: never;
    };
    "/projects/{projectID}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListPendingReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticketID}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CreateReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticketID}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Execution trace (steps logged by the agent while working) */
        get: operations["GetTrace"];
        put?: never;
        /** Append a step to the execution trace (requires valid lease) */
        post: operations["LogStep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticketID}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition ticket state (e.g. start, submit, approve, reject) */
        post: operations["TransitionTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgID}/projects/{projectID}/git-notes/commits/{commitSha}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get git notes for a commit (requires repo_path query; server returns 501 if repo not accessible) */
        get: operations["GetCommitNotes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgID}/projects/{projectID}/git-notes/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List commits with notes (requires repo_path query; server returns 501 if repo not accessible) */
        get: operations["GetGitNotesLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/escalations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListEscalations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticketID}/escalations/{escalationID}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ResolveEscalation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/queue/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ClaimTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticketID}/lease/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RenewLease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticketID}/lease": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["ReleaseLease"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MeStats: {
            /** @description Total tickets created by this agent */
            tickets_created: number;
            /** @description Total reviews approved by this agent */
            reviews_approved: number;
            /** @description Total reviews rejected by this agent */
            reviews_rejected: number;
        };
        MeStatsHistory: {
            /** @description Date strings (YYYY-MM-DD) oldest first */
            days: string[];
            /** @description Ticket count per day */
            tickets_created: number[];
            reviews_approved: number[];
            reviews_rejected: number[];
        };
        StructuredError: {
            error: string;
            /** @enum {string} */
            code: "lease_expired" | "unauthorized" | "not_found" | "conflict" | "invalid_input" | "forbidden" | "internal" | "not_implemented" | "project_closed";
            retriable: boolean;
        };
        /** @description Returned when server cannot access repo (e.g. git-notes without repo_path) */
        NotImplementedError: {
            error?: string;
            /** @enum {string} */
            code?: "not_implemented";
        };
        LogStepRequest: {
            lease_token: string;
            step: components["schemas"]["TraceStepInput"];
        };
        TraceStepInput: {
            /** @enum {string} */
            type: "tool_call" | "observation" | "thought" | "error";
            payload?: Record<string, never>;
        };
        TransitionRequest: {
            trigger: string;
            actor_id?: string;
            /** @enum {string} */
            actor?: "human" | "agent" | "system";
            payload?: Record<string, never>;
        };
        CommitNotesResponse: {
            commit_sha?: string;
            notes?: {
                [key: string]: string;
            };
        };
        GitNotesLogResponse: {
            entries?: components["schemas"]["GitNotesLogEntry"][];
        };
        GitNotesLogEntry: {
            commit_sha?: string;
            ref?: string;
            body?: string;
        };
        Org: {
            id?: string;
            name?: string;
            slug?: string;
            /** Format: date-time */
            created_at?: string;
        };
        CreateOrgRequest: {
            name?: string;
            slug?: string;
        };
        Project: {
            id?: string;
            org_id?: string;
            name?: string;
            slug?: string;
            repo_url?: string;
            /** @description Branch to checkout when closing a work stream; default "main". */
            default_branch?: string;
            tech_stack?: string[];
            context_pack?: Record<string, never>;
            /**
             * @description active (default) or closed; list endpoints default to active only.
             * @enum {string}
             */
            status?: "active" | "closed";
            /** Format: date-time */
            created_at?: string;
        };
        UpdateProjectRequest: {
            /** @enum {string} */
            status?: "active" | "closed";
            /** @description Project display name. */
            name?: string;
            /** @description URL-safe identifier (unique per org). */
            slug?: string;
            /** @description Git repo URL; when set, enables work streams + git integration (branch instructions in MCP). */
            repo_url?: string;
            /** @description Branch to checkout when closing a work stream; default "main". */
            default_branch?: string;
        };
        WorkStream: {
            id?: string;
            project_id?: string;
            name?: string;
            slug?: string;
            description?: string;
            branch?: string;
            /** @enum {string} */
            status?: "active" | "closed";
            /** Format: date-time */
            created_at?: string;
        };
        CreateWorkStreamRequest: {
            name: string;
            slug?: string;
            description?: string;
        };
        UpdateWorkStreamRequest: {
            name?: string;
            description?: string;
            branch?: string;
            /** @enum {string} */
            status?: "active" | "closed";
        };
        CreateProjectRequest: {
            name?: string;
            slug?: string;
            repo_url?: string;
            tech_stack?: string[];
        };
        Objective: {
            description?: string;
            success_criteria?: string[];
            acceptance_test?: string;
        };
        TicketContext: {
            relevant_files?: string[];
            constraints?: string[];
            prior_attempts?: Record<string, never>[];
            human_answers?: string[];
        };
        Ticket: {
            id?: string;
            project_id?: string;
            title?: string;
            /** @enum {string} */
            type?: "task" | "bug" | "spike" | "review";
            priority?: number;
            /** @enum {string} */
            state?: "pending" | "claimed" | "executing" | "awaiting_review" | "done" | "blocked" | "needs_human" | "failed";
            version?: number;
            objective?: components["schemas"]["Objective"];
            ticket_context?: components["schemas"]["TicketContext"];
            inputs?: Record<string, never>;
            outputs?: Record<string, never>;
            depends_on?: string[];
            work_stream_id?: string;
            assigned_to?: string;
            created_by?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CreateTicketRequest: {
            title: string;
            work_stream_id?: string;
            /** @enum {string} */
            type?: "task" | "bug" | "spike" | "review";
            priority?: number;
            created_by: string;
            depends_on?: string[];
            objective?: components["schemas"]["Objective"];
            ticket_context?: components["schemas"]["TicketContext"];
            /** @description Optional. Duplicate requests with the same key return the existing ticket. */
            idempotency_key?: string;
        };
        UpdateTicketRequest: {
            depends_on?: string[];
            /** @description When set, replaces the ticket title. */
            title?: string;
            /** @description Partial update; only fields present in the body are merged into the existing objective. Task/bug tickets must still have at least one of success_criteria or acceptance_test after the merge. */
            objective?: components["schemas"]["Objective"];
        };
        CreateReviewRequest: {
            /** @enum {string} */
            decision: "approved" | "rejected";
            notes?: string;
            reviewer_id?: string;
        };
        ExecutionTrace: {
            ticket_id?: string;
            agent_id?: string;
            steps?: components["schemas"]["TraceStep"][];
        };
        TraceStep: {
            id?: string;
            /** @enum {string} */
            type?: "tool_call" | "observation" | "thought" | "error";
            payload?: Record<string, never>;
            /** Format: date-time */
            created_at?: string;
        };
        PendingReviewsResponse: {
            tickets?: components["schemas"]["Ticket"][];
        };
        Escalation: {
            id?: string;
            ticket_id?: string;
            agent_id?: string;
            reason?: string;
            question?: string;
            answer?: string;
            resolved_by?: string;
            /** Format: date-time */
            resolved_at?: string;
            /** Format: date-time */
            created_at?: string;
        };
        ResolveEscalationRequest: {
            answer: string;
            reviewer_id?: string;
        };
        ClaimRequest: {
            agent_id: string;
            priority?: number;
            /** @description Optional. Retries with the same key return the same ticket/lease (renewed or re-claimed). */
            idempotency_key?: string;
        };
        ClaimResponseBody: {
            ticket?: components["schemas"]["Ticket"];
            lease?: components["schemas"]["Lease"];
        };
        Lease: {
            ticket_id?: string;
            agent_id?: string;
            token?: string;
            /** Format: date-time */
            expires_at?: string;
            renewable?: boolean;
        };
        RenewLeaseRequest: {
            lease_token: string;
        };
        RenewLeaseResponseBody: {
            /** Format: date-time */
            expires_at?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetMeStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeStats"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    GetMeStatsHistory: {
        parameters: {
            query?: {
                /** @description Number of days (default 14, max 90). */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeStatsHistory"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    ListOrgs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Org"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    CreateOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrgRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Org"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    GetOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Org"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    ListProjectsByOrg: {
        parameters: {
            query?: {
                /** @description Filter by project status; default active. */
                status?: "active" | "closed" | "all";
            };
            header?: never;
            path: {
                orgID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    CreateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    GetProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    UpdateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Bad request (e.g. invalid status) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    ListWorkStreams: {
        parameters: {
            query?: {
                /** @description Filter by status; default active. */
                status?: "active" | "closed" | "all";
            };
            header?: never;
            path: {
                projectID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkStream"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    CreateWorkStream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkStreamRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkStream"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    GetWorkStream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: string;
                workStreamID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkStream"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    UpdateWorkStream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: string;
                workStreamID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkStreamRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkStream"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    ListTickets: {
        parameters: {
            query?: {
                /** @description Filter by work stream. */
                work_stream_id?: string;
                /** @description Filter by ticket state. */
                state?: "pending" | "claimed" | "executing" | "awaiting_review" | "done" | "blocked" | "needs_human" | "failed";
            };
            header?: never;
            path: {
                projectID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    CreateTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTicketRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    GetTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    UpdateTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketID: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateTicketRequest"];
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    ListPendingReviews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingReviewsResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    CreateReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    GetTrace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionTrace"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    LogStep: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogStepRequest"];
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request (e.g. missing lease_token or step.type) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    TransitionTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request (e.g. trigger required) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    GetCommitNotes: {
        parameters: {
            query: {
                repo_path: string;
                /** @description Note type (decision, trace, or intent); omit for all types */
                type?: "decision" | "trace" | "intent";
            };
            header?: never;
            path: {
                orgID: string;
                projectID: string;
                commitSha: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitNotesResponse"];
                };
            };
            /** @description Not found (project or org mismatch) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not implemented (repo_path missing or not a git repo) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotImplementedError"];
                };
            };
        };
    };
    GetGitNotesLog: {
        parameters: {
            query: {
                repo_path: string;
                /** @description Note type (default decision) */
                type?: "decision" | "trace" | "intent";
                limit?: number;
            };
            header?: never;
            path: {
                orgID: string;
                projectID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitNotesLogResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not implemented (repo_path missing or not a git repo) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotImplementedError"];
                };
            };
        };
    };
    ListEscalations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Escalation"][];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    ResolveEscalation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketID: string;
                escalationID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveEscalationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    ClaimTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimResponseBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    RenewLease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenewLeaseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenewLeaseResponseBody"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
    ReleaseLease: {
        parameters: {
            query?: {
                lease_token?: string;
            };
            header?: never;
            path: {
                ticketID: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    lease_token?: string;
                };
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredError"];
                };
            };
        };
    };
}
